### ISSUE TITLE
UPLOAD MODEL AND TEST THE APPLICATION

### ISSUE THREAD

**Issue by AliBozdoogan** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#11]
Responsible for following task:
-Upload the trained model to the android application and observe if it detects objects which can be threats.

**Comment by aleynadede** [comment]
Created model is uploded to Android Studio, however, bugs are received regarding the size of the input which is coming from camera. The next tasks will be regarding solving these bugs.
