### ISSUE TITLE
MAKE REAL-TIME DEBUGGER FOR ANDROID STUDIO

### ISSUE THREAD

**Issue by eylulceng** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#14]
Responsible for following task:
-To be able to understand what causes the error, a real time debug mode should be activated in Android Studio. Therefore, set up the real-time debugger.

**Comment by aleynadede** [comment]
Real-time debugger is activated. By using our device, we can put breakpoints to the code and observe the variable changings.
