### ISSUE TITLE
Synchronize real time video receiving, detection and movement of the vehicle in the application 

### ISSUE THREAD

**Issue by aleynadede** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#3]
Responsible for syncronization of following steps:

-Movement of the vehicle
-Real time video receiving
-Object detection on stream

**Comment by eylulceng** [comment]
-Movement of vehicle is syncronized with the final form of the application.
-Video is received in real time successfully, and necessary updates are made in both UI and source-code.
-Object detection with limited dataset which includes only 80 objects is handled and related test operations are executed.
