### ISSUE TITLE
Synchronize Movement of the Vehicle on the Android application

### ISSUE THREAD

**Issue by eylulceng** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#4]
Responsible for following tasks:

-Synchronize movement of the vehicle in real time by using UI buttons

**Comment by AliBozdoogan** [comment]
-Package is received from buttons and it is observed in serial port.
-According to the test handled in serial port, movement of vehicle is synchronized with the UI of application.
