### ISSUE TITLE
Activate and Pair Bluetooth connection on Android application

### ISSUE THREAD

**Issue by AliBozdoogan** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#5]
Responsible for following tasks:

-Handle Bluetooth connection between vehicle and Android application by using UI buttons

**Comment by aleynadede** [comment]
-Two buttons are added to the main page.
-Communication between Bluetooth and buttons are satisfied.
-Observed that package is received from Android application successfully.
