### ISSUE TITLE
Design UI of Main Page and Handle Activity Implementations

### ISSUE THREAD

**Issue by aleynadede** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#6]
Responsible for following tasks:

-Handle front-end of main control page.
-Implement activity changes and get intents on Android application.

**Comment by AliBozdoogan** [comment]
-Front-end of each page is performed. 
-Between activities, intents are successfully linked and tests are handled.
-Buttons are worked as expected after these implementations.
