### ISSUE TITLE
Sensor Assembling and Autonomous Code Implementation

### ISSUE THREAD

**Issue by eylulceng** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#7]
Responsible for following tasks:

-Assemble the HC-SR04 sensor on KAŞİF UGV.
-Implement code of autonomous mode and execute tests of autonomous mode according to the distance data received from sensor.

**Comment by aleynadede** [comment]
-HC-SR04 sensor was mounted on KAŞİF UGV.
-Autonomous code was performed according to 27 cm interval by receiving distance information from the sensor.
-The autonomous driving test was carried out and the vehicle successfully evaded the obstacle.
-The vehicle escaped from the obstacle by moving backwards and then to the right side.
