### ISSUE TITLE
Combine Manual and Autonomous Modes and Design UI page For Autonomous Control

### ISSUE THREAD

**Issue by AliBozdoogan** [CankayaUniversity/ceng-407-408-2021-2022-Autonomous-Vehicle#8]
Responsible for following tasks:

-Combine autonomous and manual modes in single .ino file and execute tests of both modes with created buttons on UI page.

**Comment by eylulceng** [comment]
-Autonomous and manual modes are combined in a single .ino file.
-Autonomous and manual modes were matched with the buttons created on the UI page.
-The synchronization operation of the buttons has been tested.
